---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: "{{ cloud }}"
    filters:
      vm_state: active
  register: result

- name: Delete instances
  os_server:
    cloud: "{{ cloud }}"
    name: "{{ item }}"
    delete_fip: yes
    state: absent
  loop: "{{ result.openstack_servers | json_query(instancequery) }}"
  vars:
    instancequery: "[*].name"
