- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create In-memory Inventory
    add_host: 
      name: workstation-{{OSP_GUID}}.rhpds.opentlc.com
      group: workstation
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
 
- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: ospcloud
      server: 'frontend'
      filters:
        vm_state: active
    register: openstack_info
    vars:
      ansible_python_interpreter: /usr/bin/python3

  - name: Save Frontend IP
    set_fact:
      frontendIP: "{{ openstack_info.openstack_servers | json_query(instancequery) }}"
    vars:
      instancequery: "[0].accessIPv4"

  - name: Curl Frontend website
    uri:
      url: "http://{{ item }}"
      return_content: yes
    register: webpage
    loop:
      - "{{ frontendIP }}"

  - debug: var=webpage.results[0].content

  - name: Fail
    fail:
    when: "'Ansible' not in webpage.results[0].content" 

  
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Curl website
    command: curl "http://frontend1.{{ ANSIBLE_ADVANCE_GUID }}.example.opentlc.com"
    register: webpage

  - debug: var=webpage.stdout

  - name: Fail
    fail:
    when: "'Ansible' not in webpage.stdout" 
  - name: Success
    debug: msg="Congrats Yours HW Assignment is completed"
