- hosts: workstation
  gather_facts: false
  tasks:

  - name: Fetch frontent server information
    os_server_info:
      cloud: ospcloud
      server: frontend
      filters:
        vm_state: active
    register: result
    vars:
      ansible_python_interpreter: /usr/bin/python3
    tags:
      - osp.smoke

  - name: Save Frontend IP
    set_fact:
      frontendIP: "{{ result.openstack_servers | json_query(instancequery) }}"
    vars:
      instancequery: "[0].accessIPv4"
    tags:
      - osp.smoke

  - name: Curl Frontent website
    uri:
      url: "http://{{ item }}"
      return_content: yes
    register: webpage
    loop:
      - "{{ frontendIP }}"
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke
