# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

  - name: Clean OpenStack SSH keys from Ansible comments
    lineinfile:
      path: "{{ item }}"
      state: absent
      regexp: '^#'
    loop:
      - /root/.ssh/openstack.pem
      - /root/.ssh/openstack.pub

- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

