- hosts: frontends
  gather_facts: false
  tasks:

  - name: Fetch Frontent Prod Webpage
    uri:
      url: "http://{{ inventory_hostname }}"
      return_content: yes
    register: webpage
    tags:
      - osp.smoke

  - name: Fail if 'Ansible has done its job' is not in the Prod page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
    tags:
      - osp.smoke

