---
# tasks file for osp-facts
- name: Fetch Instance Info
  os_server_info:
   cloud: ospcloud
   region_name: RegionOne
   filters:
     vm_state: active
  register: result

- name: Add host and metadata group
  add_host:
   name: "{{ item.public_v4 }}"
   group: "{{ item.metadata.group }}"
  loop: "{{result.openstack_servers}}"
  loop_control:
    label: "{{ item.name }}"

- name: Add host and metadata deployment
  add_host:
   name: "{{ item.public_v4 }}"
   group: "{{ item.metadata.deployment_name }}"
  loop: "{{result.openstack_servers}}"
  loop_control:
    label: "{{ item.name }}"
