---
# vars file for base-config
repositories:
  - name: "rhel-7-server-rpms"
    description: "Red Hat Enterprise Linux 7"
    baseurl: "{{ vault_rhel-7-server-rpms_baseurl }}"
  - name: "rhel-7-server-rh-common-rpms"
    description: "Red Hat Enterprise Linux 7 Common"
    baseurl: "{{ vault_rhel-7-server-rh-common-rpms_baseurl }}"
  - name: "rhel-7-server-extras-rpms"
    description: "Red Hat Enterprise Linux 7 Extras"
    baseurl: "{{ vault_rhel-7-server-extras-rpms_baseurl }}"
  - name: "rhel-7-server-optional-rpms"
    description: "Red Hat Enterprise Linux 7 Optional"
    baseurl: "{{ vault_rhel-7-server-optional-rpms_baseurl }}"

