---
# tasks file for db-tier
  - name: Install {{ appdb_name }}
    yum:
      name: "{{ appdb_package }}"
      state: latest

  - name: Initialize {{ appdb_name }}
    command: postgresql-setup initdb
    args:
      creates: /var/lib/pgsql/data/base

  - name: Start and enable {{ appdb_name }} at boot
    service:
      name: "{{ appdb_name }}"
      enabled: yes
      state: started
